name: "minify"
description: "Minifies JS and CSS files with UglifyJS and csso"

author: "Vitaliy Kuznetsov <m@viku.me>"

inputs:
  dir:
    description: "Directory that contains the files you want to minify. Defaults to current directory (.)"
    required: false
    default: "."
  summary:
    description: "Defines if summary table should be outputed to step summary. Possible values: yes / no. Defaults to yes."
    required: false
    default: "yes"

runs:
  using: "docker"
  image: "Dockerfile"